DELETE http://localhost:8080/api/v1/vhiw/sales-logs/68e9ed4c6a478eea2cc667e1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjAyODU4MTMsImlhdCI6MTc2MDAyNjYxMywic3ViIjoiNjhlNTc4YjA0MjJiYjlmYjk4OTU1YTQ4In0.42DGIcjSwmczdBn2a6sdDSwJBi5PrAs_zrHGcG_w1oU