POST http://localhost:8080/api/v1/vhiw/sales-logs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjAwMTY5NjAsImlhdCI6MTc1OTc1Nzc2MCwic3ViIjoiNjhlMjMxZjJhMzM2YzE3Y2UwMDY1NDFjIn0.JA6Wy0kOE9ri62x6VNW9GRVtkSoRjmuJyaNc97XZexc

{
  "date": "2025-10-07T11:30:00Z",
  "opening": 6699,
  "inward": 37,
  "sales": 20,
  "outward": 0,
  "system": 6718
}

#  Initial entry
# {
#   "date": "2025-10-06T11:30:00Z",
#   "opening": 6714,
#   "inward": 0,
#   "sales": 15,
#   "outward": 0,
#   "physical": 6699,
#   "system": 6733,
#   "difference": 19,
#   "created_at": "2025-10-08T12:52:10.257Z",
#   "updated_at": "2025-10-08T12:52:10.257Z"
# }
