PUT http://localhost:8080/api/v1/vhiw/sales-logs/68e7df192639eebd62c55841
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjAyODU4MTMsImlhdCI6MTc2MDAyNjYxMywic3ViIjoiNjhlNTc4YjA0MjJiYjlmYjk4OTU1YTQ4In0.42DGIcjSwmczdBn2a6sdDSwJBi5PrAs_zrHGcG_w1oU

{
  "date": "2025-10-09T11:30:00Z",
  "inward": 0,
  "sales": 16,
  "outward": 0
}

