DELETE http://localhost:8080/api/v1/airbnb/statement/68ec86fffd00fb9d820505f0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjA0NjMyMzUsImlhdCI6MTc2MDIwNDAzNSwic3ViIjoiNjhlNTc4YjA0MjJiYjlmYjk4OTU1YTQ4In0.ezddXIeiMTLWscpF0tTKYGXM3d4JYHp2_djlwkpM4k0
